use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AHFMSearchVCServices_Example' do
  pod 'AHFMSearchVCServices', :path => '../'

  target 'AHFMSearchVCServices_Tests' do
    inherit! :search_paths

    
  end
end
